modLoader="javafml"
loaderVersion="[2,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/johni0702/bobby/issues"

[[mixins]]
config="bobby.mixins.json"

[[mixins]]
config="bobby-sodium06-compat.mixins.json"

[[mods]]
modId="bobby"
version="${version}"
displayName="Bobby"
updateJSONURL=""
displayURL="https://modrinth.com/mod/bobby"
logoFile="assets/bobby/icon.png"
authors="johni0702"
description="Allows for render distances greater than the server's view-distance setting."

[[dependencies.bobby]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.bobby]]
modId="minecraft"
type="required"
versionRange="[1.21,)"
ordering="NONE"
side="CLIENT"

[[dependencies.bobby]]
modId="cloth_config"
type="optional"
versionRange="[15.0,)"
ordering="NONE"
side="CLIENT"
